public class EdisonAHPranges {
    Public String B1L1 {get; set;}
    Public String B1R1C1 {get; set;}
    Public String B1R1C2 {get; set;}
    Public String B1R1C3 {get; set;}
    Public String B1R1C4 {get; set;}
    Public String B1R1C5 {get; set;}
    Public String B1L2 {get; set;}
    Public String B1R2C1 {get; set;}
    Public String B1R2C2 {get; set;}
    Public String B1R2C3 {get; set;}
    Public String B1R2C4 {get; set;}
    Public String B1R2C5 {get; set;}
    Public String B1L3 {get; set;}
    Public String B1R3C1 {get; set;}
    Public String B1R3C2 {get; set;}
    Public String B1R3C3 {get; set;}
    Public String B1R3C4 {get; set;}
    Public String B1R3C5 {get; set;}
    Public String B1L4 {get; set;}
    Public String B1R4C1 {get; set;}
    Public String B1R4C2 {get; set;}
    Public String B1R4C3 {get; set;}
    Public String B1R4C4 {get; set;}
    Public String B1R4C5 {get; set;}
    Public String B1L5 {get; set;}
    Public String B1R5C1 {get; set;}
    Public String B1R5C2 {get; set;}
    Public String B1R5C3 {get; set;}
    Public String B1R5C4 {get; set;}
    Public String B1R5C5 {get; set;}

    Public String B2L1 {get; set;}
    Public String B2R1C1 {get; set;}
    Public String B2R1C2 {get; set;}
    Public String B2R1C3 {get; set;}
    Public String B2R1C4 {get; set;}
    Public String B2R1C5 {get; set;}
    Public String B2L2 {get; set;}
    Public String B2R2C1 {get; set;}
    Public String B2R2C2 {get; set;}
    Public String B2R2C3 {get; set;}
    Public String B2R2C4 {get; set;}
    Public String B2R2C5 {get; set;}
    Public String B2L3 {get; set;}
    Public String B2R3C1 {get; set;}
    Public String B2R3C2 {get; set;}
    Public String B2R3C3 {get; set;}
    Public String B2R3C4 {get; set;}
    Public String B2R3C5 {get; set;}
    Public String B2L4 {get; set;}
    Public String B2R4C1 {get; set;}
    Public String B2R4C2 {get; set;}
    Public String B2R4C3 {get; set;}
    Public String B2R4C4 {get; set;}
    Public String B2R4C5 {get; set;}
    Public String B2L5 {get; set;}
    Public String B2R5C1 {get; set;}
    Public String B2R5C2 {get; set;}
    Public String B2R5C3 {get; set;}
    Public String B2R5C4 {get; set;}
    Public String B2R5C5 {get; set;}
    Public String B2L6 {get; set;}
    Public String B2R6C1 {get; set;}
    Public String B2R6C2 {get; set;}
    Public String B2R6C3 {get; set;}
    Public String B2R6C4 {get; set;}
    Public String B2R6C5 {get; set;}

    Public String B3L1 {get; set;}
    Public String B3R1C1 {get; set;}
    Public String B3R1C2 {get; set;}
    Public String B3R1C3 {get; set;}
    Public String B3R1C4 {get; set;}
    Public String B3R1C5 {get; set;}
    Public String B3L2 {get; set;}
    Public String B3R2C1 {get; set;}
    Public String B3R2C2 {get; set;}
    Public String B3R2C3 {get; set;}
    Public String B3R2C4 {get; set;}
    Public String B3R2C5 {get; set;}
    Public String B3L3 {get; set;}
    Public String B3R3C1 {get; set;}
    Public String B3R3C2 {get; set;}
    Public String B3R3C3 {get; set;}
    Public String B3R3C4 {get; set;}
    Public String B3R3C5 {get; set;}
    Public String B3L4 {get; set;}
    Public String B3R4C1 {get; set;}
    Public String B3R4C2 {get; set;}
    Public String B3R4C3 {get; set;}
    Public String B3R4C4 {get; set;}
    Public String B3R4C5 {get; set;}
    Public String B3L5 {get; set;}
    Public String B3R5C1 {get; set;}
    Public String B3R5C2 {get; set;}
    Public String B3R5C3 {get; set;}
    Public String B3R5C4 {get; set;}
    Public String B3R5C5 {get; set;}
    Public String B3L6 {get; set;}
    Public String B3R6C1 {get; set;}
    Public String B3R6C2 {get; set;}
    Public String B3R6C3 {get; set;}
    Public String B3R6C4 {get; set;}
    Public String B3R6C5 {get; set;}

    Public String B4L1 {get; set;}
    Public String B4R1C1 {get; set;}
    Public String B4R1C2 {get; set;}
    Public String B4R1C3 {get; set;}
    Public String B4R1C4 {get; set;}
    Public String B4R1C5 {get; set;}
    Public String B4L2 {get; set;}
    Public String B4R2C1 {get; set;}
    Public String B4R2C2 {get; set;}
    Public String B4R2C3 {get; set;}
    Public String B4R2C4 {get; set;}
    Public String B4R2C5 {get; set;}
    Public String B4L3 {get; set;}
    Public String B4R3C1 {get; set;}
    Public String B4R3C2 {get; set;}
    Public String B4R3C3 {get; set;}
    Public String B4R3C4 {get; set;}
    Public String B4R3C5 {get; set;}
    Public String B4L4 {get; set;}
    Public String B4R4C1 {get; set;}
    Public String B4R4C2 {get; set;}
    Public String B4R4C3 {get; set;}
    Public String B4R4C4 {get; set;}
    Public String B4R4C5 {get; set;}
    Public String B4L5 {get; set;}
    Public String B4R5C1 {get; set;}
    Public String B4R5C2 {get; set;}
    Public String B4R5C3 {get; set;}
    Public String B4R5C4 {get; set;}
    Public String B4R5C5 {get; set;}
    Public String B4L6 {get; set;}
    Public String B4R6C1 {get; set;}
    Public String B4R6C2 {get; set;}
    Public String B4R6C3 {get; set;}
    Public String B4R6C4 {get; set;}
    Public String B4R6C5 {get; set;}


    public EdisonAHPranges (){
    
    //initialize variables
    Integer Listprice = 1;
    Integer Bedrooms = 1;
    Integer HOA = 1;
    Decimal CostWithSubsidy = 1;
    Decimal tMaxMonthlyCost = 1;
    Decimal tMonthlyCosts = 1;
    Decimal tModIncome = 1;
    Integer SalePrice= 1;
    Integer Subsidy= 1;
    Decimal eq = 1;
    Decimal tax = 1;
    Decimal MortgageRate= 1;
    Decimal Insurance= 1;
    Decimal PMI= 1;
    Integer Median=1;

    // get 4-person median income, income limits for households, eq ratio, tax rate  for Edison
    Municipality__c EdisonIncomeLimit =
        [SELECT 
            Income_Limit__r.X4_Person__c,
            Equalization_Ratio__c,
            General_Tax_Rate__c
        FROM Municipality__c
        WHERE Name = 'Edison'
        LIMIT 1];
    Median = Integer.valueOf(EdisonIncomeLimit.Income_Limit__r.X4_Person__c);
    eq = EdisonIncomeLimit.Equalization_Ratio__c;
    tax = EdisonIncomeLimit.General_Tax_Rate__c;
        
    //get calculation values from custom settings
    CGPH_Profile_Custom_Settings__c cs = CGPH_Profile_Custom_Settings__c.getOrgDefaults();
    MortgageRate = cs.Mortgage_Rate__c/100;
    Insurance = cs.Insurance_4_Bedroom__c;
    PMI = cs.PMI_Rate_for_LTV_90__c;


    //1 BEDROOM
    Bedrooms = 1;
    Subsidy=40*1000;
    
    ListPrice = 150000;
    B1L1 = CurrencyFormat(ListPrice);
    B1R1C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R1C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R1C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R1C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R1C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 25000;
    B1L2 = CurrencyFormat(ListPrice);
    B1R2C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R2C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R2C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R2C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R2C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 25000;
    B1L3 = CurrencyFormat(ListPrice);
    B1R3C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R3C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R3C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R3C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R3C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 25000;
    B1L4 = CurrencyFormat(ListPrice);
    B1R4C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R4C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R4C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R4C4  = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R4C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 25000;
    B1L5 = CurrencyFormat(ListPrice);
    B1R5C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R5C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R5C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R5C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B1R5C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);

    //2 BEDROOM
    Bedrooms = 2;
    Subsidy=130*1000;
    
    ListPrice = 150000;
    B2L1 = CurrencyFormat(ListPrice);
    B2R1C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R1C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R1C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R1C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R1C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B2L2 = CurrencyFormat(ListPrice);
    B2R2C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R2C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R2C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R2C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R2C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B2L3 = CurrencyFormat(ListPrice);
    B2R3C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R3C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R3C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R3C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R3C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B2L4 = CurrencyFormat(ListPrice);
    B2R4C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R4C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R4C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R4C4  = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R4C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B2L5 = CurrencyFormat(ListPrice);
    B2R5C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R5C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R5C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R5C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R5C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B2L6 = CurrencyFormat(ListPrice);
    B2R6C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R6C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R6C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R6C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B2R6C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);

    //3 BEDROOM
    Bedrooms = 3;
    Subsidy=150*1000;
    
    ListPrice = 200000;
    B3L1 = CurrencyFormat(ListPrice);
    B3R1C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R1C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R1C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R1C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R1C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B3L2 = CurrencyFormat(ListPrice);
    B3R2C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R2C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R2C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R2C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R2C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B3L3 = CurrencyFormat(ListPrice);
    B3R3C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R3C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R3C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R3C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R3C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B3L4 = CurrencyFormat(ListPrice);
    B3R4C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R4C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R4C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R4C4  = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R4C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B3L5 = CurrencyFormat(ListPrice);
    B3R5C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R5C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R5C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R5C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R5C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B3L6 = CurrencyFormat(ListPrice);
    B3R6C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R6C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R6C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R6C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B3R6C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);

    //4 BEDROOM
    Bedrooms = 4;
    Subsidy=150*1000;
    
    ListPrice = 250000;
    B4L1 = CurrencyFormat(ListPrice);
    B4R1C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R1C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R1C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R1C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R1C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B4L2 = CurrencyFormat(ListPrice);
    B4R2C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R2C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R2C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R2C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R2C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B4L3 = CurrencyFormat(ListPrice);
    B4R3C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R3C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R3C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R3C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R3C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B4L4 = CurrencyFormat(ListPrice);
    B4R4C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R4C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R4C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R4C4  = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R4C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B4L5 = CurrencyFormat(ListPrice);
    B4R5C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R5C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R5C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R5C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R5C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    ListPrice = ListPrice + 50000;
    B4L6 = CurrencyFormat(ListPrice);
    B4R6C1 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 000 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R6C2 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 100 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R6C3 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 200 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R6C4 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 300 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);
    B4R6C5 = EligibilityGet( Bedrooms, ListPrice , ListPrice-Subsidy, 400 , Median , eq , tax ,  MortgageRate ,  Insurance , PMI);










    }
    
    Public String CurrencyFormat(Integer x){
        String c = '$';
    // ${!IF(LEN(TEXT(preAppInc))>3,LEFT(TEXT(preAppInc),LEN(TEXT(preAppInc))-3)&','&RIGHT(TEXT(preAppInc),3),'NO')}"/>
        IF (String.valueOf(x).length() > 3){
        c = c+String.valueOf(x).left(String.valueOf(x).length()-3)+','+String.valueOf(x).right(3);
        } ELSE {
        c = c+String.valueOf(x);
        }
        return c;
    }
    
    Public String EligibilityGet(Integer Bedrooms , Integer ListPrice , Integer SalePrice , Integer HOA , Integer Median , Decimal eq , Decimal tax , Decimal MortgageRate , Decimal Insurance , Decimal PMI){
        String e = '';
 
        //get Theoretical highest moderate buyer's income    
        Decimal tModIncome = tModIncomeGet(Bedrooms,Median);
        
        //get Theoretical highest monthly cost allowed to be affordable by highest moderate buyer
        Decimal tMaxMonthlyCost = tMaxMonthlyCostGet(tModIncome);
        
        //get Theoretical highest moderate buyer's monthly costs for this property w/o subsidies
        Decimal tMonthlyCosts = tMonthlyCostsGet(ListPrice,HOA,eq,tax,MortgageRate,Insurance,PMI);
        
        //get Theoretical highest moderate buyer's monthly costs for this property with subsidies and down payment assistance
        Decimal CostWithSubsidy = tMonthlyCostsGet(SalePrice,HOA,eq,tax,MortgageRate,Insurance,PMI);
        
        //property eligibility determination 0, undetermined, 1, eligible, 2, too low, 3, too high
        IF(CostWithSubsidy > tMaxMonthlyCost){
            e = 'TOO HIGH';
        } ELSE {
        IF(tMonthlyCosts < tMaxMonthlyCost){
            e = 'TOO LOW';
        } ELSE {
            e = 'ELIGIBLE';
        }
        }
    
        return e;
    }
    
    Public Decimal tModIncomeGet(Integer b,Integer m){
        Decimal tModIncomeSet = 0;
        switch on b {
            when 1 {
                tModIncomeSet = 0.7*((m * (0.7+0.8))/2);
            }   
            when 2 {
                tModIncomeSet = 0.7*(m * 0.9);
            }
            when 3 {
            tModIncomeSet = 0.7 * ((m * (1+1.08))/2);
            }
            when 4 {
            tModIncomeSet = 0.7*( m *1.16);
            }
            when 5 {
            tModIncomeSet = 0.7*(m *1.16);
            }
            when else {
            tModIncomeSet = 0;
            }
        }
        return tModIncomeSet;
    }
    
    Public Decimal tMaxMonthlyCostGet(Decimal x){
        Decimal tMaxMonthlyCostSet = x *0.28/12;
        return tMaxMonthlyCostSet;
    
    }
    
    Public Decimal tMonthlyCostsGet(Integer lp,Integer h,Decimal eq, Decimal tax, Decimal mort, Decimal ins, Decimal pmi){
        Decimal tMonthlyCostsSet = ((lp*0.95)*(mort/12))/(1 - math.pow(Double.valueof(1+(mort/12)),(-1*30*12)))+h+ins+(((lp*eq)/10000)*(tax/12))+((lp*0.95)/1000*(( pmi*1000 /12)));
        return tMonthlyCostsSet;
    }
    

}